#include "customString.h"
#include "terrain.h"
#include "error.h"
#include "fweHeader.h"
#include "util.h"
#include <math.h>


void
writeTerrainFile(
	char* filename,
	char* out,
	int8_t finalize)
{
	// open File
	FILE* inFile = fopen(
		filename,
		"r");
	if(!inFile)
	{
		Error_warning("Unable to open terrain file, skipping");
		return;
	}

	// read file line by line
	char line[120] = {0};
	char tmp = 0;
	Memory* header = 0;
	Polygon *pol = 0;
	Terrain *ter = 0;
	while(fgets(line, sizeof(line), inFile))
	{
		switch(line[0])
		{
			// map environment info (header)
			case 'm':
			{
				char environment[120] = {0};

				sscanf(
					line, 
					"%c %s", 
					&tmp, 
					environment);

				header = FweHeader_create(
					environment);
			}break;

			// polygon list
			case 'p':
			{
				if(!pol)
				{
					pol = Polygon_create();
				}
				float x = 0;
				float y = 0;
				int surface = 0;
				char surfaceName[120] = {0};
				sscanf(
					line,
					"%c %f %f %i %s",
					&tmp,
					&x,
					&y,
					&surface,
					surfaceName);
				Polygon_add(
					pol, 
					x,
					y,
					(int8_t)surface,
					surfaceName);
			} break;

			// terrain list
			case 't':
			{
				if(!ter)
				{
					ter = Terrain_create();
				}
				char terrainName[120] = {0};
				char surfaceName[120] = {0};
				int team = 0;
				int surface = 0;
				int foundation = 0;
				int mine = 0;
				int windfloor = 0;
				int viewfloor = 0;
				int nodraw = 0;
				sscanf(
					line,
					"%c %s %s %i %i %i %i %i %i %i",
					&tmp,
					terrainName,
					surfaceName,
					&team,
					&surface,
					&foundation,
					&mine,
					&windfloor,
					&viewfloor,
					&nodraw);
				Terrain_add(
					ter, 
					pol, 
					terrainName,
					surfaceName,
					(int32_t)team,
					(int8_t)surface,
					(int8_t)foundation,
					(int8_t)mine,
					(int8_t)windfloor,
					(int8_t)viewfloor,
					(int8_t)nodraw);
				// we shouldn't free pol, since ter contains its
				// elements
				pol = 0;
			}
		}
	}
	// header
	if(!header)
	{
		Error_message("No Header specified: appending!");
	}
	else
	{
		Util_writeVoidArrayFile(
			0,
			out,
			header->data,
			header->size);
	}
	if(!ter)
	{
		Error_message("No Terrain specified: skipping");
	}
	else
	{
		// body
		Memory* rawOut = Terrain_toMemory(ter);
		if(!finalize)
		{
			// yeah, i know, don't repeat yourself yadda yadda
			rawOut->size -= sizeof(uint64_t);
		}
		Util_writeVoidArrayFile(
			1,
			out, 
			rawOut->data, 
			rawOut->size);
	}

	// close File
	fclose(
		inFile);
}

void
printHelp()
{
	const char help[] = 
		"specify a terrain file with \"-t [FILE]\"\n"
		"specify a output file with \"-o [FILE] (endings get autogenerated)\"\n"
		"to allow for further editing, use \"-nf\"(don't finalize)\n"
		"terrain file specification can be extacted from the readme";
	printf("%s\n",help);
}

// they system is my garbage collector
int main(
	int argc, 
	char* argv[])
{
	// getting options 
	char* outputTerrainFile = 0;
	char* terrainFile = 0;
	int8_t finalize = 1;
	for(int i = 0; i < argc; i++, argv++)
	{
		if(strcmp(*argv, "-o") == 0)
		{
			i++;
			argv++;
			outputTerrainFile=(char*)calloc(
				1,
				strlen(*argv+4));
			strcat(
				outputTerrainFile, 
				*argv);
			strcat(
				outputTerrainFile, 
				".fwe");
		}
		else if (strcmp(*argv, "-t") == 0)
		{
			i++;
			argv++;
			terrainFile=*argv;
		}
		else if (strcmp(*argv, "-nf") == 0)
		{
			finalize = 0;
		}
		else if (strcmp(*argv, "-h") == 0)
		{
			printHelp();
		}
	}
	if(!outputTerrainFile && terrainFile)
	{
		outputTerrainFile = "out.fwe";
	}
	if(!terrainFile)
	{
		printHelp();
	}
	// parse and write input file
	else
	{
		writeTerrainFile(
			terrainFile, 
			outputTerrainFile,
			finalize);
	}
	return 0;
}
