#include "customString.h"
#include "terrain.h"
#include "error.h"
#include "fweHeader.h"
#include "util.h"
#include <math.h>

void
writeBracingFile(
	char* filename,
	char* out)
{
	
}

void
writeTerrainFile(
	char* filename,
	char* out)
{
	// open File
	FILE* inFile = fopen(
		filename,
		"r");
	if(!inFile)
	{
		Error_warning("Unable to open terrain file, skipping");
		return;
	}

	// read file line by line
	char line[120] = {0};
	char tmp = 0;
	Memory* header = 0;
	Polygon *pol = 0;
	Terrain *ter = 0;
	while(fgets(line, sizeof(line), inFile))
	{
		switch(line[0])
		{
			// map environment info (header)
			case 'm':
			{
				char environment[120] = {0};

				sscanf(
					line, 
					"%c %s", 
					&tmp, 
					environment);

				header = FweHeader_create(
					header, 
					environment);
			}break;

			// polygon list
			case 'p':
			{
				if(!pol)
				{
					pol = Polygon_create(pol);
				}
				float x = 0;
				float y = 0;
				int surface = 0;
				char surfaceName[120] = {0};
				sscanf(
					line,
					"%c %f %f %i %s",
					&tmp,
					&x,
					&y,
					&surface,
					surfaceName);
				Polygon_add(
					pol, 
					x,
					y,
					(int8_t)surface,
					surfaceName);
			} break;

			// terrain list
			case 't':
			{
				if(!ter)
				{
					ter = Terrain_create(ter);
				}
				char terrainName[120] = {0};
				char surfaceName[120] = {0};
				int team = 0;
				int surface = 0;
				int foundation = 0;
				int mine = 0;
				int windfloor = 0;
				int viewfloor = 0;
				int nodraw = 0;
				sscanf(
					line,
					"%c %s %s %i %i %i %i %i %i %i",
					&tmp,
					terrainName,
					surfaceName,
					&team,
					&surface,
					&foundation,
					&mine,
					&windfloor,
					&viewfloor,
					&nodraw);
				Terrain_add(
					ter, 
					pol, 
					terrainName,
					surfaceName,
					(int32_t)team,
					(int8_t)surface,
					(int8_t)foundation,
					(int8_t)mine,
					(int8_t)windfloor,
					(int8_t)viewfloor,
					(int8_t)nodraw);
				// we shouldn't free pol, since ter contains its
				// elements
				pol = 0;
			}
		}
	}
	if(!ter || !header)
	{
		Error_warning("Failed to create the Terrain file. Skipping");
		return;
	}

	// header
	Util_writeVoidArrayFile(
		0,
		out,
		header->data,
		header->size);

	// body
	Memory* rawOut = Terrain_toMemory(ter);
	Util_writeVoidArrayFile(
		1,
		out, 
		rawOut->data, 
		rawOut->size);

	// close File
	fclose(
		inFile);
}

void
printHelp()
{
	const char help[] = 
		"specify a terrain file with \"-t [FILE]\"\n"
		"specify a bracing and device file with \"-b [FILE] (NYI)\"\n"
		"specify a output file with \"-o [FILE] (endings get autogenerated)\"\n"
		"terrain and bracing/device file specification can be extacted from the readme";
	printf("%s\n",help);
}

// they system is my garbage collector
int main(
	int argc, 
	char* argv[])
{
	// getting options 
	char* outputTerrainFile = 0;
	char* outputBracingFile = 0;
	char* terrainFile = 0;
	char* bracingFile = 0;
	for(int i = 0; i < argc; i++, argv++)
	{
		if(strcmp(*argv, "-o") == 0)
		{
			i++;
			argv++;
			outputTerrainFile=(char*)calloc(
				1,
				strlen(*argv+4));
			outputBracingFile=(char*)calloc(
				1,
				strlen(*argv+4));

			strcat(
				outputTerrainFile, 
				*argv);
			strcat(
				outputBracingFile, 
				*argv);

			strcat(
				outputTerrainFile, 
				".fwe");
			strcat(
				outputBracingFile, 
				".spr");
		}
		else if (strcmp(*argv, "-t") == 0)
		{
			i++;
			argv++;
			terrainFile=*argv;
		}
		else if (strcmp(*argv, "-b") == 0)
		{
			i++;
			argv++;
			bracingFile=*argv;
		}
	}
	if(!outputTerrainFile && terrainFile)
	{
		outputTerrainFile = "out.fwe";
	}
	if(!outputTerrainFile && bracingFile)
	{
		outputTerrainFile = "out.spr";
	}
	if(!terrainFile && !bracingFile)
	{
		printHelp();
	}
	
	// parse and write input files
	if(terrainFile)
	{
		writeTerrainFile(
			terrainFile, 
			outputTerrainFile);
	}
	if(bracingFile)
	{
		writeBracingFile(
			bracingFile, 
			outputBracingFile);
	}
	return 0;
	// old stuff
	Terrain *ter = 0;
	ter = Terrain_create(ter);
	Polygon *pol = 0;
	pol = Polygon_create(pol);
	Polygon_add(pol, 0 , 100000, false, "");
	for(float x = -9999; x < 0; x+=1)
	{
		float y = x/2 + sin(0.005*x)*255;
		Polygon_add(pol, x, y, true, "rocks01");
	}
	for(float x = 0; x < 10000; x+=50)
	{
		float y = x/2 + sin(0.005*x)*255;
		Polygon_add(pol, x, y, false, "rocks01");
	}
	Terrain_add(ter, pol, "environment/alpine/ground/ground1.dds","rocks01", 1, false ,true, true, true, false, false);
	Memory* header = 0;
	header = FweHeader_create(header, "environment/alpine");
	Memory* mem = Terrain_toMemory(ter);
	Util_writeVoidArrayFile(0,"surface_test_01.fwe", header->data, header->size);
	Util_writeVoidArrayFile(1,"surface_test_01.fwe", mem->data, mem->size);
	return 0;
}
